language: java
jdk:
  - openjdk8

branches:
  only:
    - develop

before_install:
  - chmod +x mvnw

# Travis CI
cache:
  directories:
    - $HOME/.m2a
    -
notifications:
  email:
    - riyenas0925@gmail.com
    - rlagksml99@gmail.com
    - 2kyung19@gmail.com